### ISSUE TITLE
DNS过期？

### ISSUE THREAD

**Issue by N0el4kLs** [SEC-CAFE/sec.cafe#1]
大佬，你的网站貌似访问不了了
<img width="767" alt="image" src="https://github.com/SEC-CAFE/sec.cafe/assets/64629436/87ebe220-a8d7-44c0-a9d2-d736a161730e">

**Comment by fooying** [comment]
域名备案，临时域名解析是sec.style
不过当前已完成备案，预计今日恢复原域名sec.cafe
